name: Run meeting bot

on:
  schedule:
    - cron: '20 16 * * *'

jobs:
  run_bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - run: python meeting_leader_bot.py
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_APP_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}
          MEETING_CHANNEL_ID: ${{ secrets.MEETING_CHANNEL_ID }}
